import { validationResult } from "express-validator";

export const handleInputErrors = (req, res, next) => {    // middleware function to handle input validation errors generated by the express-validator 
  const errors = validationResult(req)                   //  const errors to check for validation errors using express-validator
}
