import { validationResult } from "express-validator";     // import { validationResult } to retrieve the validation result object from the request.

export const handleInputErrors = (req, res, next) => {    // middleware function to handle input validation errors generated by the express-validator 
  const errors = validationResult(req)                   //  const errors to check for validation errors using express-validator

  if (!errors.isEmpty()) {                            // three paramters req (the request object) and res (the response object) 
    res.status(400);                                  // and next is a callback function to pass control to the next middleware
    res.json({ errors: errors.array() });             //  (!errors.isEmpty()). to checks If there are validation errors 
  }                                                   // It sets the response status to 400 Bad Request.
}                                                    // It sends a JSON response containing an array of validation errors using errors.array().
